# Generated by Django 3.2.12 on 2022-05-10 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_watch_venue_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='venue_image',
            new_name='image',
        ),
    ]
