# Generated by Django 3.2.12 on 2022-05-12 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_watch_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indication_type_name', models.CharField(max_length=65)),
            ],
            options={
                'db_table': 'indication_type',
            },
        ),
        migrations.RunSQL("insert into indication_type(indication_type_name) values('Стрелочная'), ('Электронная'), ('Стрелочная и электронная')"),
        migrations.AddField(
            model_name='watch',
            name='indication_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='mainapp.indicationtype'),
            preserve_default=False,
        ),
    ]
