# Generated by Django 3.2.12 on 2022-05-13 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0005_auto_20220512_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=75)),
            ],
            options={
                'db_table': 'feature',
            },
        ),
        migrations.RemoveField(
            model_name='watch',
            name='backlight',
        ),
        migrations.CreateModel(
            name='WatchHasFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mainapp.feature')),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.watch')),
            ],
            options={
                'db_table': 'watch_has_feature',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.watch')),
            ],
            options={
                'db_table': 'rate',
            },
        ),
    ]
