# Generated by Django 3.2.12 on 2022-05-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20220513_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='value',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
