# Generated by Django 3.2.12 on 2022-05-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_watch_feature_list'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='watchhasfeature',
            constraint=models.UniqueConstraint(fields=('watch', 'feature'), name='unique_watch_feature'),
        ),
    ]
