# Generated by Django 3.2.12 on 2022-05-25 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20220525_1444'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='watchhasfeature',
            name='unique_watch_feature',
        ),
        migrations.AlterField(
            model_name='watchhasfeature',
            name='watch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.watch'),
        ),
    ]
