# Generated by Django 3.2.12 on 2022-05-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20220525_1445'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchhasfeature',
            unique_together={('watch', 'feature')},
        ),
    ]
