# Generated by Django 3.2.12 on 2022-05-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_watchhasfeature_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchHasFeature',
        ),
    ]
