# Generated by Django 3.2.12 on 2022-05-25 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_watchhasfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 5, 25), null=True),
        ),
        migrations.AlterUniqueTogether(
            name='watchhasfeature',
            unique_together=set(),
        ),
    ]
