# Generated by Django 3.2.12 on 2022-05-25 14:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0015_auto_20220525_1700'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderhasproduct',
            unique_together={('order', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('watch', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='watchhasfeature',
            unique_together={('watch', 'feature')},
        ),
    ]
