# Generated by Django 3.2.12 on 2022-05-29 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20220525_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='warranty',
        ),
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 5, 29), null=True),
        ),
    ]
