# Generated by Django 3.2.12 on 2022-05-29 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20220529_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='mainapp.gender'),
        ),
    ]
