# Generated by Django 3.2.12 on 2022-06-08 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_alter_order_locality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mainapp.locality'),
        ),
    ]
