# Generated by Django 3.2.12 on 2022-06-11 16:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_auto_20220609_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhasproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mainapp.order'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 6, 11), null=True),
        ),
    ]
