# Generated by Django 3.2.12 on 2022-06-11 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_auto_20220611_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhasproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.order'),
        ),
    ]
