# Generated by Django 3.2.12 on 2022-06-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_alter_orderhasproduct_noted_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhasproduct',
            name='noted_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
