# Generated by Django 3.2.12 on 2022-06-17 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_auto_20220617_0449'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS ohp_change_order; \
                CREATE TRIGGER ohp_change_order \
                AFTER UPDATE ON `Order` \
                FOR EACH ROW \
                BEGIN \
                IF old.order_state_id NOT IN( \
                    SELECT id  \
                    FROM Order_State  \
                    WHERE order_state_name IN('Корзина', 'Не оплачен','Отклонен')) \
                AND new.order_state_id IN( \
                    SELECT id  \
                    FROM Order_State  \
                    WHERE order_state_name IN('Корзина', 'Не оплачен', 'Отклонен'))  \
                THEN UPDATE Watch w   \
                    SET current_amount = current_amount + (  \
                        SELECT quantity  \
                        FROM Order_Has_Product  \
                        WHERE product_id = w.id  \
                        AND order_id = new.id)  \
                    WHERE id IN(  \
                        SELECT product_id  \
                        FROM Order_Has_Product \
                        WHERE order_id = new.id); \
                ELSEIF old.order_state_id IN( \
                    SELECT id  \
                    FROM Order_State  \
                    WHERE order_state_name IN('Корзина', 'Не оплачен','Отклонен')) \
                AND new.order_state_id NOT IN( \
                    SELECT id  \
                    FROM Order_State  \
                    WHERE order_state_name IN('Корзина', 'Не оплачен','Отклонен')) \
                THEN UPDATE Watch w  \
                    SET current_amount = current_amount - ( \
                        SELECT quantity  \
                        FROM Order_Has_Product  \
                        WHERE product_id = w.id  \
                        AND order_id = new.id)  \
                    WHERE id IN( \
                        SELECT product_id  \
                        FROM Order_Has_Product  \
                        WHERE order_id = new.id); \
                END IF; \
                END; "
        ),

    ]
