# Generated by Django 3.2.12 on 2022-06-17 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_addtrig1'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS ohp_update; \
                CREATE TRIGGER ohp_update \
                AFTER UPDATE ON Order_Has_Product \
                FOR EACH ROW \
                BEGIN \
                IF old.quantity <> new.quantity AND (SELECT \
                order_state_id FROM `Order` WHERE id = old.order_id LIMIT 1) \
                NOT IN(SELECT id FROM Order_State WHERE \
                order_state_name IN('Корзина', 'Не оплачен', 'Отклонен', \
                'Оплачен'))THEN \
                UPDATE Watch SET current_amount = current_amount + old.quantity \
                - new.quantity WHERE id = old.product_id; \
                END IF; \
                END;"
        ),

    ]
