# Generated by Django 3.2.12 on 2022-06-17 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_addtrig3'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS cart_insert; \
                CREATE TRIGGER cart_insert \
                BEFORE INSERT ON `Order` \
                FOR EACH ROW \
                BEGIN \
                IF new.order_state_id = (SELECT id  \
                    FROM Order_State \
                    WHERE order_state_name = 'Корзина' LIMIT 1) \
                AND EXISTS(SELECT *  \
                    FROM `Order` o  \
                    INNER JOIN Order_State os  \
                    ON o.order_state_id = os.id  \
                    WHERE o.user_id = new.user_id  \
                    AND os.order_state_name = 'Корзина')  \
                THEN \
                    SET @n = new.user_id; \
                    SET @msg = CONCAT('Cant create the cart for user with id = ', \
                    @n, ', he already have it!'); \
                    SIGNAL SQLSTATE '45000' SET MYSQL_ERRNO=30062, \
                    MESSAGE_TEXT=@msg;  \
                END IF; \
                END;"
        ),

    ]
