# Generated by Django 3.2.12 on 2022-06-17 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_addtrig4'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS update_cart; \
                CREATE TRIGGER update_cart \
                BEFORE UPDATE ON `Order` \
                FOR EACH ROW \
                BEGIN \
                IF (SELECT order_state_name  \
                    FROM Order_State  \
                    WHERE id = new.order_state_id LIMIT 1) = 'Корзина' \
                AND new.order_state_id <> old.order_state_id THEN \
                    SET @n = old.id; \
                    SET @msg = CONCAT('Cant change the state of the order with id = \
                    ', @n, ' back to Корзина !'); \
                    SIGNAL SQLSTATE '45000' SET MYSQL_ERRNO=30060, \
                    MESSAGE_TEXT=@msg; \
                END IF; \
                END;"
        ),

    ]
