# Generated by Django 3.2.12 on 2022-06-17 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_addtrig5'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS note_costs; \
                CREATE TRIGGER note_costs \
                BEFORE UPDATE ON `Order` \
                FOR EACH ROW \
                BEGIN \
                IF (SELECT order_state_name  \
                    FROM Order_State  \
                    WHERE id = old.order_state_id LIMIT 1) = 'Корзина' \
                AND new.order_state_id <> old.order_state_id THEN \
                    UPDATE Order_Has_Product ohp \
                    SET noted_cost = (SELECT model_cost  \
                        FROM Watch  \
                        WHERE id=ohp.product_id) \
                    WHERE order_id=new.id; \
                END IF; \
                END;"
        ),

    ]
